# Generated by Django 4.2.5 on 2023-09-24 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="content",
            new_name="answer",
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
