# Generated by Django 4.2.5 on 2023-09-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0002_rename_content_question_answer_question_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
