# Generated by Django 4.2.5 on 2023-09-26 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0003_question_published_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
